src/exsm3951_bookswap/exsm3951_bookswap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('bookswap.urls')),
	path('', include('authentication.urls')),
    path('library/', include('bookswap.urls')),
    path('notifications/', include('notifications.urls')),
    path('profile/', include('profile.urls')),
    path('help/', include('help.urls')),
]

src/exsm3951_bookswap/help/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('faq/', views.faq_view, name='help_faq'),
]

src/exsm3951_bookswap/bookswap/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from authentication.models import Member
from django.utils import timezone
from django.core.exceptions import ValidationError
from decimal import Decimal


def validate_not_future_date(value):
    if value > timezone.now().date():
        raise ValidationError("Publication Date cannot be in the future")

def validate_shipment_date(value):
    if value < timezone.now().date():
        raise ValidationError("Shipment cannot be in the past")
    
    
isbn_validator = RegexValidator(
    regex=r'^(?:\d{9}[\dXx]|\d{13})$',
    message="Enter a valid ISBN-10 or ISBN-13 number without dashes."
)

class Book(models.Model):
    class Language(models.TextChoices):
        english = 'en', 'English'
        french = 'fr', 'French'
        
    isbn = models.CharField(max_length=100, null=False, unique=True, db_index=True, validators=[isbn_validator])
    title = models.CharField(max_length=100, null=False, db_index=True)
    author = models.CharField(max_length=100, null=False, db_index=True)
    genre = models.CharField(max_length=100, null=False)
    description = models.TextField()
    pub_date = models.DateField(null=False, validators=[validate_not_future_date])
    language = models.CharField(max_length=100, choices=Language.choices, default=Language.english, null=False)  
    weight = models.DecimalField(max_digits=7, decimal_places=2, default=0.1, null=False)
    image_url = models.TextField(default="No image", null=False)

    def __str__(self):
        return self.title
    
class LibraryItem(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)
    member = models.ForeignKey(Member, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return f"{self.book.title}"    


class BookListing(models.Model):
    
    class BookCondition(models.TextChoices):
        new = "New"
        good = "Good"
        fair = "Fair"
        poor = "Poor"
        
    library_item = models.ForeignKey(LibraryItem, on_delete=models.CASCADE, null=True)
    member_owner = models.ForeignKey(Member, on_delete=models.CASCADE, null=False, related_name='book_listings')
    condition = models.CharField(
        max_length=4,
        choices=BookCondition.choices, default=BookCondition.new, null=False
    )
    price =  models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(Decimal("0.01"))], null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_closed = models.BooleanField(default=False, null=False)
    
    
    def __str__(self):
        return f"{self.library_item.book.title} (${self.price})"
    

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)
    member = models.ForeignKey(Member, on_delete=models.SET_NULL, null=True)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], null=True)
    review = models.TextField()
    
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.book.title}: {self.rating}"
    
    class Meta:
        unique_together = ('book', 'member')

"""
Many-to-many table 
A member can have many books on their wish list
A book can be part of many members' wish list
"""
class WishList(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)
    member = models.ForeignKey(Member, on_delete=models.CASCADE, null=False)

    #make sure the combination of member and book is unique
    class Meta:
        unique_together = ('member', 'book')
        

class Shipment(models.Model):
    shipment_date = models.DateField(null=False, validators=[validate_shipment_date])
    shipment_cost = models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(0.00)], null=False)
    weight = models.DecimalField(max_digits=7, decimal_places=3, default=0.01, validators=[MinValueValidator(0.01)], null=False)
    address = models.TextField(max_length=255, blank=False, null=False)
    
    
class Transaction(models.Model):
    
    class TransactionType(models.TextChoices):
        sale = "Sale"
        swap = "Swap"
        
    class TransactionStatus(models.TextChoices):
        pending = "Pending"
        accepted = "Accepted"
        rejected = "Rejected"
        
        
    transaction_type = models.CharField(max_length=4, choices=TransactionType.choices, null=False)
    transaction_status = models.CharField(max_length=8, choices=TransactionStatus.choices, default=TransactionStatus.pending, null=False)
    transaction_date = models.DateField(auto_now_add=True, null=False)
    initiator_member = models.ForeignKey(Member, related_name="initiator_member", on_delete=models.CASCADE, null=False)
    receiver_member = models.ForeignKey(Member, related_name="receiver_member", on_delete=models.CASCADE, null=False)
    

    def clean(self):
        super().clean()
        if self.initiator_member == self.receiver_member:
            raise ValidationError("A member cannot sell/swap with themselves")
    
    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)  


class TransactionDetail(models.Model):
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, null=False, related_name='transaction_details')
    book_listing = models.ForeignKey(BookListing, on_delete=models.CASCADE, null=False)
    from_member = models.ForeignKey(Member, related_name="transaction_detail_from_member", on_delete=models.CASCADE, null=False)
    to_member = models.ForeignKey(Member, related_name="transaction_detail_to_member", on_delete=models.CASCADE, null=False)
    shipment = models.ForeignKey(Shipment, on_delete=models.CASCADE, null=False)
    cost = models.DecimalField(max_digits=6, decimal_places=2, null=False,  default=Decimal("0.00"))
    
    def clean(self):
        super().clean()
        if self.from_member == self.to_member:
            raise ValidationError("A member cannot transfer a library item with themselves")
    
        if self.book_listing.is_closed:
            raise ValidationError("Cannot create a transaction detail with a closed book listing")
    
    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)  

src/exsm3951_bookswap/templates/transactions/swap-form.html
{% extends "base.html" %} {% load bookswap_tags %} {% block title %}
Swap Form {% endblock %} {% block content %}

<div
  class="max-w-4xl mx-auto bg-amber-50 rounded-xl shadow-md p-6 text-[#825d3f]"
>
  <h2 class="text-5xl font-bold mb-4 flex justify-center">
    <span> Lets Make a Swap! </span>
  </h2>
  <form method="POST" action="{% url 'swap_offer_view' book_listing.id %}" class="space-y-4">
    {% csrf_token %}

    {{ form.errors }}
    <!-- <h1>Option 1</h1>
    <div class="overflow-auto" style="height: 200px">
        {% for checkbox in form.book_listings %}
        <div class="flex items-center ps-4 border border-gray-200 rounded-sm dark:border-gray-700">
            <label class="w-full py-4 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                {{ checkbox.tag }}
                {{ checkbox.choice_label }}
            </label>
        </div>
        {% endfor %}
    </div> -->

    <div class="flex space-x-8">
      <div class="flex-col">
        <h2 class="mb-6 text-2xl text-center text-[#825d3f]">
          Step One:<br>
          Select at least one of your book listings to offer.
        </h2>
        <ul class="grid w-full gap-2 grid-cols-1 overflow-auto" style="max-height: 550px;">
            {% for checkbox in form.selected_book_listings %}
                {% with book_listing=my_book_listings_dict|get_item:checkbox.data.value %}
                <li>
                    <input
                        type="checkbox"
                        name="selected_book_listings"
                        id="{{ checkbox.id_for_label }}"
                        value="{{ checkbox.data.value }}"
                        class="hidden peer"
                        {% if checkbox.data.checked %}checked{% endif %}
                    >
                    <label
                        for="{{ checkbox.id_for_label }}"
                        class="inline-flex p-4 items-center w-full justify-between text-gray-500 bg-amber-50 border-2 border-amber-300 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-green-600 dark:peer-checked:border-green-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-amber-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700"
                    >                           
                        <!-- <div class="block flex justify-between"> -->
                            <div>
                                <div class="text-lg font-semibold">{{ book_listing.library_item.book.title }}</div>
                                <div class="w-full text-md">Price: ${{ book_listing.price }}</div>
                            </div>
                            <img src="{{ book_listing.library_item.book.image_url }}" style="height: 100px" alt="No Image found"/>
                        <!-- </div> -->
                    </label>
                </li>
                {% endwith %}
            {% endfor %}
        </ul>
      </div>
      <div class="flex-col">
        <h2 class="mb-6 text-2xl text-center text-[#825d3f]">
          Step Two:<br>
           Select the book you want<br>
           in exchange.
        </h2>
      <div
          class="inline-flex items-center justify-between w-full p-5 text-[#825d3f] bg-amber-50 border-2 border-amber-300 rounded-xl dark dark:border-gray-700 peer-checked:border-green-600 dark:peer-checked:border-green-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 dark:text-gray-400 dark:bg-gray-800 dark"
        >
          <div class="block flex">
            <div>
              <div class="w-full text-lg font-semibold">
                {{ book_listing.library_item.book.title }}
              </div>
              <div class="w-full text-md">Price: ${{ book_listing.price }}</div>
            </div>
            <img
              src="{{ book_listing.library_item.book.image_url }}"
              alt="No Image found"
            />
          </div>
        </div>
        <p>
           Owned by: {{ book_listing.member_owner.full_name }}
        </p>
      </div>
    </div>


    <button type="submit"
            class="w-full bg-green-600 text-white py-2 px-4 rounded-xl hover:bg-green-700 transition">
      Offer Swap
    </button>
    <div class="w-full max-w-4xl mx-auto mb-6 flex justify-center">
      <a href="{% url 'all_listings' %}"
        class="bg-pink-400 text-white px-4 py-2 rounded-xl hover:bg-pink-500 transition text-center">
        Cancel
      </a>
    </div>
  </form>
</div>

{% endblock %}

src/exsm3951_bookswap/templates/transactions/transaction.html
{% extends "base.html" %} {% load bookswap_tags %} {% block title %}
Transaction{% endblock %} {% block content %}

<!-- Display the Listing -->
<div
  class="max-w-full mx-auto bg-amber-50 rounded-xl shadow-md p-6 text-[#825d3f]"
>
  <h2 class="text-5xl font-bold mb-4 flex justify-center">
    <span> {{ transaction.transaction_type }} Books? </span>
  </h2>
  <div class="p-3 text-center mb-4">
  {% if transaction.transaction_type == 'Sale' %}
  <!-- Sale Transaction -->
    <h3>Details:</h3>
    {% for detail in transaction.transaction_details.all %}
    <div class="bg-amber-50 shadow-lg p-3 rounded-xl">
      <p class="font-bold">{{ detail.book_listing.library_item.book.title }}</p>
      <p class="text-sm text-gray-600">
        Author: {{ detail.book_listing.library_item.book.author }}
      </p>
      <p class="text-md">${{ detail.book_listing.price }}</p>
      <p class="text-md">Shipping Address: {{ detail.shipment.address }}</p>
      <p class="text-md">
        Transfers to member: {{ detail.to_member.full_name }}
      </p>
      <img
        src="{{ detail.book_listing.library_item.book.image_url }}"
        alt="No image"
      />
    </div>
    {% endfor %}
  {% else %}
    <!-- Swap Transaction -->
    <div class="flex space-x-8">
      <div class="flex-col">
        <h2 class="mb-6 text-center text-2xl">
          {{ transaction.receiver_member.full_name }} Receives:
        </h2>
        <ul class="grid w-full gap-2 grid-cols-1 overflow-auto" style="max-height: 550px;">
          {% with initiator_details=transaction.transaction_details.all|get_details_filter_by_from_member:transaction.initiator_member %}
            {% for detail in initiator_details %}
              <li>
                  <div
                      class="inline-flex p-4 items-center w-full justify-between text-[#825d3f] bg-amber-50 border-2 border-amber-300 rounded-xl dark dark:border-gray-700 peer-checked:border-blue-600 dark:peer-checked:border-blue-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 dark:text-gray-400 dark:bg-gray-800 dark"
                  >
                    <div>
                        <div class="w-full text-lg font-semibold">{{ detail.book_listing.library_item.book.title }}</div>
                        <div class="w-full text-md text-[#825d3f]">Price: ${{ detail.book_listing.price }}</div>
                    </div>
                    <img src="{{ detail.book_listing.library_item.book.image_url }}" style="height: 100px" alt="No Image found"/>
                  </div>
              </li>
            {% endfor %}
          {% endwith %}
        </ul>
      </div>
      <div class="flex-col">
        <h2 class="mb-6 text-center text-2xl">
           {{ transaction.initiator_member.full_name }} Receives:
        </h2>
        {% with receiver_details=transaction.transaction_details.all|get_details_filter_by_from_member:transaction.receiver_member %}
          {% for detail in receiver_details %}
          <div
            class="inline-flex items-center justify-between w-full p-5 text-gray-500 bg-amber-50 border-2 border-amber-300 rounded-xl dark dark:border-gray-700 peer-checked:border-blue-600 dark:peer-checked:border-blue-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 dark:text-gray-400 dark:bg-gray-800 dark"
          >
            <div class="block flex">
              <div>
                <div class="w-full text-lg text-[#825d3f] font-semibold">
                  {{ detail.book_listing.library_item.book.title }}
                </div>
                <div class="w-full text-md text-[#825d3f]">Price: ${{ detail.book_listing.price }}</div>
              </div>
              <img
                src="{{ detail.book_listing.library_item.book.image_url }}"
                alt="No Image found"
              />
            </div>
          </div>
          {% endfor %}
        {% endwith %}
      </div>
    </div>
    {% endif %}
  </div>

  <!-- Action button / status result -->
  <!-- Only the user that can accept/reject the transaction should see the action buttons -->
  {% if transaction.receiver_member == user and transaction.transaction_status == 'Pending' %}
  <div class="flex flex-wrap gap-10 justify-center mt-4">
    <form
      class="inline"
      method="POST"
      action="{% url 'accept_transaction' transaction.id %}"
    >
      {% csrf_token %}
      <button
        type="submit"
        class="text-white bg-gradient-to-br from-green-600 to-green-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-xl text-md px-5 py-1.5 text-center"
      >
        Accept
      </button>
    </form>
    <form
      class="inline"
      method="POST"
      action="{% url 'reject_transaction' transaction.id %}"
    >
      {% csrf_token %}
      <button
        type="submit"
        class="text-white bg-gradient-to-br from-pink-600 to-pink-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-xl text-md px-5 py-1.5 text-center"
      >
        Reject
      </button>
    </form>
  </div>
  {% elif transaction.transaction_status == 'Pending' %}
  <div class="flex flex-wrap gap-9 justify-center mt-4">
    This transaction is {{ transaction.get_transaction_status_display }}
  </div>
  {% else %}
  <div class="flex flex-wrap gap-9 justify-center mt-4">
    This transaction was {{ transaction.get_transaction_status_display }}
  </div>
  {% endif %}
  <br>
  <div class="w-full max-w-4xl mx-auto mb-6 flex justify-center">
    <a href="{% url 'transactions_view' %}"
       class="bg-pink-400 text-white px-4 py-2 rounded-xl hover:bg-pink-500 transition text-center">
      Close
    </a>
  </div>
</div>

{% endblock %}

src/exsm3951_bookswap/templates/transactions/transactions.html
{% extends "base.html" %} {% block title %}Transactions - BookSwap{% endblock %}
{% load bookswap_tags %}
{% block content %}

<div class="text-center">
  <h2
    class="text-6xl font-semibold inline-block mb-6 px-6 py-2 rounded-xl backdrop-blur-lg"
    style="
      color: #825d3f;
      background-color: rgba(255, 255, 255, 0.4);
      text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);
    "
  >
    Transactions
  </h2>
</div>

{% for transaction in transactions %}
<a
  href="/library/transactions/{{transaction.id}}"
  class="block p-6 m-6 text-[#825d3f] {% if transaction.transaction_status == 'Pending'%} bg-pink-100 {% elif transaction.transaction_status == 'Accepted'%} bg-green-200 {% else %}bg-red-200{% endif %} border border-amber-400 rounded-xl shadow-lg hover:bg-blue-200 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
>
  <h5
    class="mb-2 text-2xl font-bold tracking-tight text-[#825d3f] dark:text-white"
  >
    {{ transaction.transaction_type }} Transaction ({{ transaction.transaction_status }}) 
  </h5>

  {% if transaction.transaction_type == 'Sale' %}
    <p class="font-normal text-[#825d3f]">
      {% if transaction.initiator_member == user %}
        <div>
          You offered to buy:
        </div>
      {% else %}
        <div>
          {{ transaction.initiator_member }} offered to buy the book from you:
        </div>
      {% endif %}
      {% for detail in transaction.transaction_details.all %}
        <div>
          <strong>
            {{ detail.book_listing.library_item.book.title }}
          </strong>
        </div>
      {% endfor %}
    </p>
  {% else %}
    <p class="font-normal text-[#825d3f]">
      <!-- You initiated the swap transaction -->
      {% if transaction.initiator_member == user %}
        {% with initiator_details=transaction.transaction_details.all|get_details_filter_by_from_member:transaction.initiator_member %}
          {% for detail in initiator_details %}
            <p>
              You offered to swap your book listing: {{ detail.book_listing.library_item.book.title }}
            </p>
          {% endfor %}
        {% endwith %}
        <hr class="w-full h-1 mx-auto my-4 bg-amber-50 border-0 rounded-xl my-4">
        {% with receiver_details=transaction.transaction_details.all|get_details_filter_by_from_member:transaction.receiver_member %}
          {% for detail in receiver_details %}
            <p>
              You want to receive the book listing from {{ detail.from_member.full_name }}: {{ detail.book_listing.library_item.book.title }}
            </p>
          {% endfor %}
        {% endwith %}
      {% else %}
        <!-- You did not initiate the swap transaction -->
        {% with receiver_details=transaction.transaction_details.all|get_details_filter_by_from_member:transaction.receiver_member %}
          {% for detail in receiver_details %}
            <p>
              {{ detail.to_member.full_name }} wants to receive your book listing: {{ detail.book_listing.library_item.book.title }}
            </p>
          {% endfor %}
        {% endwith %}
        <hr class="w-full h-1 mx-auto my-4 bg-gray-500 border-0 rounded-sm my-4">
        {% with initiator_details=transaction.transaction_details.all|get_details_filter_by_from_member:transaction.initiator_member %}
          {% for detail in initiator_details %}
            <p>
              {{ detail.from_member.full_name }} wants to give you the book listing: {{ detail.book_listing.library_item.book.title }}
            </p>
          {% endfor %}
        {% endwith %}
      {% endif %}
    </p>

  {% endif %}

  
</a>
{% empty %}
<div class="text-[#825d3f]">No transaction.</div>
{% endfor %} {% endblock %}